### ISSUE TITLE
Library doesn't recognize Fibaro Dimmer 2

### ISSUE THREAD

**Issue by bluewalk** [genielabs/zwave-lib-dotnet#12] opened 2017-03-08 06:20 UTC
The library does allow the controller to add the Fibaro Dimmer 2 node and lists it as follows:

> Node
 4
___Manufacturer Specific 010F-0102-1000
___Basic Type None
___Generic Type None
___Specific Type 0
___Secure Info Frame
___Info Frame 04-11-01-5E-86-72-59-73-22-31-32-71-56-98-7A
___Node Version info:
______LibraryType 3
______ProtocolVersion 4
______ProtocolSubVersion 5
______ApplicationVersion 3
______ApplicationSubVersion 4

As you can see Generic Type is set to None stopping me from sending the SwitchMultilevel command. Also the commandclasses are empty. Does this has to do witht he fact the Fibaro's are using encryption? As I also have a normal LED light which works just fine:

> Node 2
___Manufacturer Specific --
___Basic Type RoutingSlave
___Generic Type SwitchMultilevel
___Specific Type 1
___Secure Info Frame
___Info Frame
___Routing Info 01

**Comment by bluewalk** [comment] 2017-03-08 06:32
Okay after the third discovery it finally notices the dimmer.

> Node 4
___Manufacturer Specific 010F-0102-1000
___Basic Type RoutingSlave
___Generic Type SwitchMultilevel
___Specific Type 1
___Secure Info Frame
___Info Frame 04-11-01-5E-86-72-59-73-22-31-32-71-56-98-7A
___Node Version info:
______LibraryType 3
______ProtocolVersion 4
______ProtocolSubVersion 5
______ApplicationVersion 3
______ApplicationSubVersion 4

Any idea why this might occur?

[EDIT]
Finally at home, started testing and it still didn't work, so instead of using the 
            `controller.BeginNodeAdd();
I used the button on the AEOTEC Z-Stick to include the device into the network and promptly it started to work. Any idea why the BeginNodeAdd doesn't work properly?

**Comment by genemars** [comment] 2017-06-05 01:15
@bluewalk  the device must be close to the controller. Was that the case perhaps?

**Comment by bluewalk** [comment] 2017-06-06 05:53
Hi, no unfortunately not. Calling the AddNodes doesn't work properly with the AEOTEC Z-Stick. I had to press the button on the AEOTEC Z-Stick itself to include the node. Problem solved :)

**Comment by Bounz** [comment] 2017-06-06 06:05
Hi, @bluewalk.
What version of AEOTEC Z-Stick are you use using?

**Comment by bluewalk** [comment] 2017-06-06 09:40
I have the Gen 5, will look at the label on the back later today when I get home

**Comment by bluewalk** [comment] 2017-06-06 15:09
@Bounz This one :)
![img_3483](https://user-images.githubusercontent.com/6522477/26836335-db55d0ea-4ada-11e7-85f5-9e2f7540070c.JPG)

**Comment by Bounz** [comment] 2017-06-07 11:42
Well, I'm using RaZberry board and can't reproduce the problem with the inclusion of the device.
But recently I've ordered the same AEOTEC Z-Stick, so I'll try to investigate this problem when the package arrives.

**Comment by Bounz** [comment] 2017-06-24 16:21
Hi, @bluewalk.
Got my Aeotec Z-Stick Gen5 two days ago. I'll try to reproduce problems with devices inclusion using software "inclusion" mode.

**Comment by genemars** [comment] 2017-06-24 16:24
@Bounz  I see there might be more work to commit. So I wait for your confirmation before publishing the new nuget package.

**Comment by Bounz** [comment] 2017-06-25 11:19
@bluewalk, I tested inclusion and exclusion of the devices with Aeotec Z-Stick and ZWaveLib and everything works as expected. I used Fibaro Door/Window Sensor and Fibaro Dimmer (1st edition).
Two notes here:

- For the first test, I was including and excluding Fibaro Door/Window Sensor. It failed for the first few times before I realized that the instruction "Press TMP button quickly 3 times" means really quickly;
- During inclusion process, while requesting node information, the device may go sleep, and you should wake it up (but it doesn't seem to be your case because dimmer is mains powered).

@genemars, I think you can continue with the new nuget package.

**Comment by genemars** [comment] 2017-06-25 12:35
@Bounz @bluewalk , new version 1.0.15 published. Shall we close this issue?

**Comment by bluewalk** [comment] 2017-06-25 15:20
@genemars You can close this issue yes, I will test the software inclusion again when installing a new dimmer :-)

**Closed as completed** 2017-06-25 15:28 UTC
